services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_VERSION} # Use the GitLab Edition image
    restart: always # Always restart the container if it stops
    env_file:
      - .env
    container_name: gitlab-ce
    hostname: "${GITLAB_DOMAIN}"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "22:22" # SSH

    volumes:
      - /mnt/gitlab/config:/etc/gitlab
      - /mnt/gitlab/logs:/var/log/gitlab
      - /mnt/gitlab/data:/var/opt/gitlab
      - ./config/gitlab.rb:/etc/gitlab/gitlab.rb # Mount external gitlab setup

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    env_file:
      - .env
    container_name: gitlab-runner
    network_mode: 'host'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gitlab/config/ssl:/etc/gitlab-runner/certs
    environment:
      - GITLAB_DOMAIN=${GITLAB_DOMAIN}
      - GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}
    entrypoint: ["/bin/bash", "/config/runner.sh"]
