services:
  runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: runner
    env_file:
      - .env
    network_mode: 'host'
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner.sh:/scripts/runner.sh
    entrypoint: ["/bin/bash", "/scripts/runner.sh"]

volumes:
  runner-config: